services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  binance_ingestor:
    build: .
    container_name: binance_ingestor
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    restart: always

  cassandra:
    image: cassandra:5.0
    container_name: cassandra
    restart: always
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "CryptoCluster"
      CASSANDRA_NUM_TOKENS: 4
      CASSANDRA_START_RPC: "true"
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 100M
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'describe keyspaces'"]
      interval: 30s
      timeout: 10s
      retries: 5

  cassandra-init:
    image: cassandra:5.0
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./scripts/init_cassandra.cql:/init/init_cassandra.cql
    entrypoint: ["/bin/bash", "-c", "sleep 10 && cqlsh cassandra -f /init/init_cassandra.cql"]


volumes:
  cassandra_data:
  pg_data:
